# JDK: 1.8
# 'adpot' distribution 

name: Android CI

on:
  push:
    branches: [ "WritingTests" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: gradle

    # caches (saves) files for later so we save cpu time for future CI builds
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-cache-${{ runner.os }}-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    # run the login unit tests
    - name: Run Login Unit Tests
      run: ./gradlew testDebugUnitTest --tests com.example.frugl_app.LoginUtilTest

    # run the signup unit tests
    - name: Run Signup Unit Tests
      run: ./gradlew testDebugUnitTest --tests com.example.frugl_app.SignUpUtilTest

    # uploads test results to a file in the repo 
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: app/build/reports/tests/testDebugUnitTest/

